cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/php'
tap 'homebrew/services'
brew 'autoconf'
brew 'bash-completion'
brew 'coreutils'
brew 'pkg-config'
brew 'dnsmasq', service_restart: true
brew 'libpng'
brew 'freetype'
brew 'gettext'
brew 'git'
brew 'grc'
brew 'icu4c'
brew 'jpeg'
brew 'libxml2'
brew 'libyaml'
brew 'openssl'
brew 'mysql', service_restart: true
brew 'ruby-build'
brew 'rbenv'
brew 'readline'
brew 'ruby'
brew 'spark'
brew 'unixodbc'
brew 'homebrew/php/brew-php-switcher'
brew 'homebrew/php/php56'
brew 'homebrew/php/php56-xdebug'
brew 'wget'

# brew 'ack'
# brew 'go'
# brew 'imagemagick'
# brew 'jp2a'
# brew 'libcaca', args: ['with-imlib2']
# brew 'libgit2'
# brew 'node'
# brew 'postgresql'
# brew 'roundup'
# brew 'spaceman-diff'
# brew 'unrar'
# brew 'wget'
# brew 'youtube-dl'
#
# cask '1password'
# cask 'atom'
# cask 'garmin-express'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'mapbox-studio'
# cask 'seashore'
# cask 'steam'
# cask 'transmission'
# cask 'tunnelbear'
# cask 'vlc'
