#!/usr/bin/env bash

#########################################
#          OLD        #
#########################################

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null;
done;

# Source the RVM. (Load RVM into a shell session *as a function*)

#if [ -s `$HOME/.rvm/scripts/rvm` ]; then
#	source $HOME/.rvm/scripts/rvm
#fi

#########
# Aliases and Other Stuff #
#########
if [ -f ~/.dotfiles/bash/bash_aliases ]; then
  . ~/.dotfiles/bash/bash_aliases
fi

if [ -f ~/.dotfiles/drupal/drupal.alias ]; then
  . ~/.dotfiles/drupal/drupal.alias
fi

if [ -f ~/.dotfiles/git/git.alias ]; then
  . ~/.dotfiles/git/git.alias
fi

if [ -f ~/.dotfiles/mounts/mounts.sh ]; then
  . ~/.dotfiles/mounts/mounts.sh
fi


#########################################
#                Exports                #
#########################################
# Export global vars...
export RBENV_ROOT=/usr/local/var/rbenv
export XDEBUG_CONFIG="idekey=PHPSTORM1"

# Uncomment the code lines below for terminal colors:
# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1
# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export LS_COLORS='di=1:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rb=90'
export COLOR_NC='\\e[0m' # No Color
export COLOR_WHITE='\\e[1;37m'
export COLOR_BLACK='\\e[0;30m'
export COLOR_BLUE='\\e[0;34m'
export COLOR_LIGHT_BLUE='\\e[1;34m'
export COLOR_GREEN='\\e[0;32m'
export COLOR_LIGHT_GREEN='\\e[1;32m'
export COLOR_CYAN='\\e[0;36m'
export COLOR_LIGHT_CYAN='\\e[1;36m'
export COLOR_RED='\\e[0;31m'
export COLOR_LIGHT_RED='\\e[1;31m'
export COLOR_PURPLE='\\e[0;35m'
export COLOR_LIGHT_PURPLE='\\e[1;35m'
export COLOR_BROWN='\\e[0;33m'
export COLOR_YELLOW='\\e[1;33m'
export COLOR_GRAY='\\e[0;30m'
export COLOR_LIGHT_GRAY='\\e[0;37m'
